### ISSUE TITLE
How to interpret eval results?

### ISSUE THREAD

**Issue by BraunBenni** [hailanyi/CasA#13]
Hi,

im struggling with interpreting the results of the evaluation of the KITTI data.

Can somebody please explain how to read those results e.g.:
```
Car AP@0.70, 0.70, 0.70:
bbox AP:90.8339, 90.0913, 89.7052
bev  AP:90.3835, 88.7014, 88.1821
3d   AP:89.8144, 86.5609, 79.3242
aos  AP:90.81, 90.01, 89.55
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:96.9829, 95.9043, 93.4644
bev  AP:93.9380, 90.2077, 87.7245
3d   AP:93.0861, 86.3323, 81.8653
aos  AP:96.96, 95.77, 93.28
Car AP@0.70, 0.50, 0.50:
bbox AP:90.8339, 90.0913, 89.7052
bev  AP:98.5752, 90.0662, 89.7175
3d   AP:90.8197, 90.0441, 89.6911
aos  AP:90.81, 90.01, 89.55
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:96.9829, 95.9043, 93.4644
bev  AP:99.1163, 95.9381, 93.4898
3d   AP:96.9698, 95.8939, 93.4472
aos  AP:96.96, 95.77, 93.28
```

I already got the difference between AP and AP_R40. 
Do the three columns stand for the three difficulty levels (easy, moderate, hard)?
What are e.g. `0.70, 0.50, 0.50` in the header of every block standing for?

As I am quite new to this topic, any help would be highly appreciated.

**Comment by hailanyi** [comment]
KITTI leadboard uses moderate Car 3D AP (R40) for ranking, which is **86.3323** in your results. Some literature also reports moderate Car 3D AP (R11), which is **86.5609** in your results.


Car AP@0.70, 0.70, 0.70:              # IoU threshold for metric calculation （IoU=0.7）
bbox AP:90.8339, 90.0913, 89.7052  # 2D AP(R11) on image plane for easy, moderate and hard split
bev  AP:90.3835, 88.7014, 88.1821    # Rotated 2D AP(R11) on BEV plane for easy, moderate and hard split
3d   AP:89.8144, **_86.5609_**, 79.3242    # 3D AP(R11) in 3D space for easy, **_moderate_** and hard split
aos  AP:90.81, 90.01, 89.55               # orientation similarity for easy, moderate and hard split
Car AP_R40@0.70, 0.70, 0.70:           # IoU threshold for metric calculation
bbox AP:96.9829, 95.9043, 93.4644  # 2D AP(R40) on image plane for easy, moderate and hard split
bev  AP:93.9380, 90.2077, 87.7245   # Rotated 2D AP(R40) on BEV plane for easy, moderate and hard split
3d   AP:93.0861,  **_86.3323_**, 81.8653    # 3D AP(R40) in 3D space for easy, **_moderate_** and hard split
aos  AP:96.96, 95.77, 93.28                # orientation similarity for easy, moderate and hard split


The metric below is the same as above, but the IoU threshold is different.


Car AP@0.70, 0.50, 0.50:               # IoU threshold for metric calculation （IoU=0.5）
bbox AP:90.8339, 90.0913, 89.7052   
bev  AP:98.5752, 90.0662, 89.7175
3d   AP:90.8197, 90.0441, 89.6911
aos  AP:90.81, 90.01, 89.55
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:96.9829, 95.9043, 93.4644
bev  AP:99.1163, 95.9381, 93.4898
3d   AP:96.9698, 95.8939, 93.4472
aos  AP:96.96, 95.77, 93.28

**Comment by BraunBenni** [comment]
Thanks for the quick response! It did help a lot.

Just one more question to make sure I got it: 
`Cyclist AP_R40@0.50, 0.50, 0.50:` --> IoU threshold = 0.5
`Cyclist AP_R40@0.50, 0.25, 0.25:` --> IoU threshold = 0.25
Why is the header then `0.50 0.25 0.25` instead of just `0.25`? Is there a specific meaning or is only the last number relevant?

**Comment by hailanyi** [comment]
I think maybe the first 0.5 means that the bbox metric is calculated by 0.5 threshold, because the bbox results are the same under both ```AP_R40@0.50, 0.50, 0.50:``` and ```AP_R40@0.50, 0.25, 0.25:```

**Comment by BraunBenni** [comment]
Thanks for your help and work in general!
