### ISSUE TITLE
About anchor_head_singlev2.

### ISSUE THREAD

**Issue by Raiden-cn** [hailanyi/CasA#14]
Is this a trick about  'get_anchor_mask'?
I am confuse about this aapear in CasA and TED.
It doesn't show up in original pcdet.

**Comment by hailanyi** [comment]
Yes, this is a small trick to speed up the anchor and ground truth association. The original codes associate all dense anchors with ground truth by a IoU threshold, which is time-consuming. Indeed, the anchors in the non-points region cannot be associated with any ground truth. So the IoU calculation is unnecessary. I removed such anchors by the 'get_anchor_mask' to slightly speed up the detector training.
