### ISSUE TITLE
Question for score threshold

### ISSUE THREAD

**Issue by dyzxzeng** [hailanyi/CasA#15]
We need to use a slightly lower score threshold for test split. Does the scor threshold stand for the value in POST_PEOCESSING or other configs? And why we need to use a lower one? I tried some lower value for POST_PEOCESSING's SCORE_THRESHOLD, and find increase in number of objects per sample. Is that the reason?

**Comment by hailanyi** [comment]
Yes, the score threshold refers to the POST_PEOCESSING's SCORE_THRESHOLD.
