### ISSUE TITLE
小白求助！！！

### ISSUE THREAD

**Issue by DZ2584793260** [hailanyi/CasA#3]
作者您好！
我们想把模型转成onnx，请问可以把发布的pth文件转成onnx上传吗

**Comment by hailanyi** [comment]
我没有计划上传onnx格式，如果你有需要，你自己可以任意修改我上传的pth文件.

**Comment by DZ2584793260** [comment]
好的，非常感谢！

**Comment by hailanyi** [comment]
抱歉，目前没这个计划，你可以自己尝试加载我们的模型，然后重新保存一下
