### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by xuyanging** [hailanyi/CasA#5]
hi, rhank you for your work, I have some problems.

step1.  I changed the input point cloud from a single camera to multiple cameras( modify get_fov_flag function), using a dataset similar to nuscene.
step2. I changed POINT_CLOUD_RANGE from [0, -40, -3, 70.4, 40, 1] to [-51.2, -51.2, -3.0, 51.2, 51.2, 1.0] and  change GRID_OFFSETS: from [0., 40.] to [0., 0.] 

but training loss is unstable and results are terrible, only a few cars are detected.

I'd like to ask for your some advices on how to change  the code or configuration, Thx!

**Comment by hailanyi** [comment]
You can refer to waymo's [config](https://github.com/hailanyi/CasA/blob/master/tools/cfgs/waymo_models/CasA-V.yaml), as waymo also perform 360-degree detection. If you use POINT_CLOUD_RANGE =  [-51.2, -51.2, -3.0, 51.2, 51.2, 1.0] , the GRID_OFFSETS should be  [51.2, 51.2]. Note that kitti's coordinate system is based on the ground at -1.7m, please ensure that the ground of your data set is also about -1.7m.
