### ISSUE TITLE
小白求助！

### ISSUE THREAD

**Issue by HechongLi** [hailanyi/CasA#8]
作者您好，如果已经配置好openpcdet环境了的话，运行这个程序还需要在配置好的openpcdet的环境里面进行develop嘛？运行的时候需要把相关的yaml文件等放到openpcdet那个项目里面嘛，因为运行时候的ROOT_DIR好像显示的是openpcdet所在的位置，运行的时候也会显示KeyError，应该怎么解决呢？

**Comment by hailanyi** [comment]
可以尝试以下两个解决方法：（1）卸载openpcdet重新安装CasA；（2）直接安装CasA，如果还是不能用就把CasA的路径加到python路径里。

**Comment by HechongLi** [comment]
> 可以尝试以下两个解决方法：（1）卸载openpcdet重新安装CasA；（2）直接安装CasA，如果还是不能用就把CasA的路径加到python路径里。

嗯嗯好的，非常感谢！
